### ISSUE TITLE
Add `compiled/` to .eslintignore

### ISSUE THREAD

**Issue by bendtherules** [tanem/generator-typescript-react-lib#103]
This happens when:
1. Have one unsuccessful run of `npm run test` - so cleanup code doesn't run and stray compiled/ directory is not removed
2. Run it once again and now eslint also looks at files in `compiled/` dir and finds errors. Ideally, it should always ignore it.

Suggestion:
Add `compiled/` to .eslintignore

**Comment by tanem** [comment]
Thanks @bendtherules :pray: Created #104 to address this, will release shortly.

**Comment by tanem** [comment]
Released in `v1.0.29`.
