### ISSUE TITLE
Add github_changelog_generator to devdependencies

### ISSUE THREAD

**Issue by bendtherules** [tanem/generator-typescript-react-lib#107]
`npm version patch` fails as `github_changelog_generator` is not installed. We should add it to devdependencies.
Because it has some prominent forks now, not sure which one was initially assumed.

Again some docs helps here (related to #106) as this changelog packages assume few things related to how Github PR, tags, issues and branches should be configured for the release. Else, i's a black box for new users.

**Comment by tanem** [comment]
Hey @bendtherules, this should be addressed in #108. `github_changelog_generator` was a ruby dep that I started having trouble with, so I ended up writing my own scripts for personal projects.

Just have to tidy a few things up on other repos, then will get back to some docs :wink:

**Comment by tanem** [comment]
Released in `v1.0.30`. Will address docs via #106.
