### ISSUE TITLE
Not providing "UMD global variable name" causes rollup build to error

### ISSUE THREAD

**Issue by TjaartBroodryk** [tanem/generator-typescript-react-lib#189]
I mistakenly didnt provide a value to the `UMD global variable name` prompt, which caused rollup throw `Error: You must supply "output.name" for UMD bundles.`

Should the UMD prompt be marked as `required`? Or is it behaving as designed, and I just misused it?

I'm happy to raise a PR for this, if you think that action is needed.

**Comment by tanem** [comment]
Hey @TjaartBroodryk. It's a glitch, and `required` is probably the simplest way of solving it.

Thinking about it some more though, it might be nicer to provide a default value based on the [`defaultPackageName`](https://github.com/tanem/generator-typescript-react-lib/blob/master/generators/app/index.js#L15)?

Something like:

```js
// Pseudo lodash-fp code!
const defaultUmdGlobalName = pipe(
  words,
  map(upperFirst),
  join('')
)(defaultPackageName);

...

{
  type: 'input',
  name: 'umdGlobalName',
  message: 'UMD global variable name:',
  default: defaultUmdGlobalName
}
```

**Comment by TjaartBroodryk** [comment]
Yeah, the default is a better solution! 

Will raise a PR now
